name: BP TypeScript Utilities CI

on:
  push:
    branches:
      # hyphen indicates list item
      - master
      - develop
      - feature/*
jobs:
  lint:
    name: lint
    runs-on: windows-latest
    steps:
      - run: npm lint
  test:
    name: test
    needs: lint
    runs-on: windows-latest
    steps:
      - run: npm test
  build:
    name: build
    needs: [ lint, test ]
    runs-on: windows-latest
    steps:
      - run: npm run build