name: BP TypeScript Utilities CI

on:
  push:
    branches:
      # hyphen indicates list item
      - master
      - develop
      - feature/*
jobs:
  ci:
    name: ci
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
  lint:
    name: lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Linting all files with .ts file extension"
          npm ci
          npm run lint
  test:
    name: test
    needs: lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Running all unit tests"
          npm ci
          npm test
  build:
    name: build
    needs: [ lint, test ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Building application"
          npm ci
          npm run build