name: BP TypeScript Utilities CI

on:
  push:
    branches:
      # hyphen indicates list item
      - master
      - develop
      - feature/*
jobs:
  lint:
    name: lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm ci
          npm run lint
  test:
    name: test
    needs: lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm ci
          npm test
  build:
    name: build
    needs: [ lint, test ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm ci
          npm run build
  publish:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          npm install
          - if: contains(github.event.head_commit.message, 'MAJOR')
          echo Upgrading Major (1.x.x) Version
          npm version major
          - if: contains(github.event.head_commit.message, 'MINOR')
          echo Upgrading Minor (x.1.x) Version
          npm version minor
          - if: contains(github.event.head_commit.message, 'PATCH')
          echo Patch/Bug Fix (x.x.1)
          npm version patch
          echo Building and Publishing
          npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: '829c99a9-3408-47de-86cb-6ee18501827c'